= Graphryder

Graphryder builds and displays network graphs that describe conversations on Discourse platforms annotated with OpenEthnographer. This manual documents how to set up the Graphryder stack from scratch.

[Graphryder import script](https://github.com/edgeryders/graphryder-import-script) exports data from a Discourse & OpenEthnographer postgresql database and builds a Neo4j graph database from that data.
Graphryder Neo4j database is the data layer of Graphryder.
Graphryder GraphQL API and dashboard (this repository) are deployed together in a Docker container and are how the end user interacts with the network graphs.

See the Edgeryders platform for [installation instructions](https://edgeryders.eu/t/ryderex-installation-manual/16314) of the entire stack.

== How to install with docker

=== Requirements

To be able to install the application on your server, you will need :

* docker & docker-compose
* git

On debian like system, you can install them with the following command :
`apt-get install git docker docker-compose`

=== Process

* Clone the repository in the folder `/opt`

`$>git clone https://github.com/edgeryders/graphryder`

* Create a linux user called `graphryder`

`$>useradd graphryder -d /opt/graphryder/ -M -r -s /bin/bash`

* Add the created user to the group `docker`

`$> usermod -aG docker graphryder`

* Change the owner of the folder `/opt/graphryder`

`$>chown -R graphryder:graphryder /opt/graphryder`

* Add the env variable `MODE` like this: `echo 'export MODE="prod"' >> ~/.bashrc`

* Create the system script service :

[source,bash]
----
$> cd /etc/systemd/system/
$> vi graphryder.service
[Unit]
Description=graphryder
Requires=docker.service

After=docker.service
[Service]
Restart=always
User=graphryder
Group=graphryder
WorkingDirectory=/opt/graphryder/docker

# Shutdown container (if running) when unit is started
ExecStartPre=docker-compose -f docker-compose.yml down
# Start container when unit is started
ExecStart=docker-compose -f docker-compose.yml up
# Stop container when unit is stopped
ExecStop=docker-compose -f docker-compose.yml down

[Install]
WantedBy=multi-user.target
$> sudo systemctl enable graphryder.service
----

* When it's done, you can start the stack by running this command : `systemctl start graphryder.service`

TIP: You can check the log of the process with the command `journalctl -u graphryder.service`

Wait some minutes (the build of the docker stack can takes ~10min), and open your favorite browser on http://localchost
(you can replace localhost by the name/ip of your server)
